/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.fibonacci.Fibonacci;
import org.example.fibonacci.FibonacciRecursive;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


public class App {
    private static final Logger logger = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) {
        Fibonacci fibonacci = new Fibonacci(new FibonacciRecursive());
        logger.info("Fibonacci(10) = {}", fibonacci.exec(10));
    }
}
