site_name: 実践プログラミングエクササイズ 2025
site_description: 実践プログラミングエクササイズ 2025
site_author: k2works
repo_url: https://github.com/k2works/pragmatic-programing-exercise-2025
repo_name: pragmatic-programing-exercise-2025

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight

extra_css:
  - ops/docker/mkdocs/assets/css/extra.css

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: plantuml
          class: plantuml
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.emoji
  - admonition
  - toc:
      permalink: true
  - plantuml_markdown:
      server: http://plantuml:8080/plantuml
      format: svg

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10.6.1/dist/mermaid.min.js
  - ops/docker/mkdocs/assets/js/extra.js

extra:
  plantuml_url: http://www.plantuml.com/plantuml
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername/go-ddd
      name: GitHub Repository

plugins:
  - search

nav:
  - Journal:
    - 2025-05-31: journal/20250531.md
